# Generated by Django 5.2.1 on 2025-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
