# Generated by Django 5.2.1 on 2025-05-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicant_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobprofile',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='business_type',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='custom_duties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='applications.jobprofile'),
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='duties',
            field=models.JSONField(default=list),
        ),
    ]
