# Generated by Django 5.2.1 on 2025-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='business_type',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HC', 'Healthcare'), ('CON', 'Construction'), ('EDU', 'Education'), ('MFG', 'Manufacturing'), ('RET', 'Retail'), ('FIN', 'Financial Services'), ('HOS', 'Hospitality'), ('TRN', 'Transportation'), ('OTH', 'Other')], default='OTH', max_length=5),
        ),
    ]
