# Generated by Django 5.2.1 on 2025-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_applicant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='contract_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='contract_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv_template',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='motivation_letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='motivation_letter_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='motivation_letter_template',
            field=models.TextField(blank=True),
        ),
    ]
