# Generated by Django 5.2.1 on 2025-06-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_applicant_agent_fee_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
