# Generated by Django 5.2.1 on 2025-06-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_jobprofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='updated_at',
        ),
    ]
