# Generated by Django 5.2.1 on 2025-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_jobprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='is_other',
            field=models.BooleanField(default=False, help_text="Check this if this is the 'Other' option that allows custom job titles"),
        ),
    ]
