# Generated by Django 5.2.1 on 2025-06-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_jobprofile_is_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='is_other',
        ),
    ]
