# Generated by Django 5.2.1 on 2025-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_jobprofile_is_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applying_for',
            field=models.CharField(choices=[('general', 'General Work Permit'), ('waiver', 'Waiver'), ('none', 'Not Applicable')], default='none', max_length=10, verbose_name='Applying for'),
        ),
    ]
