# Generated by Django 5.2.1 on 2025-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_applicantsession_applicant_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='subjects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
