# Generated by Django 5.2.1 on 2025-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_applicant_commencement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='employed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
