# Generated by Django 5.2.1 on 2025-06-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_applicant_employed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='custom_duties',
        ),
    ]
