# Generated by Django 5.2.1 on 2025-06-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_remove_applicant_custom_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='business_type',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('HC', 'Healthcare'), ('CON', 'Construction'), ('EDU', 'Education'), ('MFG', 'Manufacturing'), ('RET', 'Retail'), ('FIN', 'Financial Services'), ('HOS', 'Hospitality'), ('TRN', 'Transportation'), ('OTH', 'Other')], max_length=5, null=True),
        ),
    ]
