# Generated by Django 5.2.1 on 2025-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_alter_applicant_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='custom_duties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
