# Generated by Django 5.2.1 on 2025-06-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicant_custom_duties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='business_type',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HC', 'Healthcare'), ('CON', 'Construction'), ('EDU', 'Education'), ('MFG', 'Manufacturing'), ('RET', 'Retail'), ('FIN', 'Financial Services'), ('HOS', 'Hospitality'), ('TRN', 'Transportation'), ('OTH', 'Other')], default='OTH', max_length=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='commencement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Commencement Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='employer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
