# Generated by Django 5.2.1 on 2025-06-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_applicant_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applying_for',
            field=models.CharField(choices=[('general', 'General Work Permit'), ('waiver', 'Waiver'), ('none', 'Select Permit Type')], default='none', max_length=10, verbose_name='Applying for'),
        ),
    ]
